---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hpp
spec:
  selector:
    matchLabels:
      app: hpp
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: hpp
        tier: frontend
    spec:
      containers:
      - name: master
        image: pcfkubo/hot-potato:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: hpp
  labels:
    app: hpp
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 9000
  selector:
    app: hpp
    tier: frontend
